import { afterEach, beforeEach, describe, expect, test } from 'bun:test';
import { existsSync, mkdirSync, readdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { runAgentsSync } from './agents';

describe('agents sync command', () => {
	let testDir: string;
	let originalCwd: string;

	beforeEach(() => {
		originalCwd = process.cwd();
		testDir = join(import.meta.dir, `test-agents-${Date.now()}-${Math.random()}`);
		mkdirSync(testDir, { recursive: true });
		process.chdir(testDir);

		// Create omni directory structure
		mkdirSync('omni/capabilities', { recursive: true });
		mkdirSync('.omni', { recursive: true });
	});

	afterEach(() => {
		process.chdir(originalCwd);
		if (existsSync(testDir)) {
			rmSync(testDir, { recursive: true, force: true });
		}
	});

	test('should create required directories', async () => {
		// Create minimal config
		await Bun.write(
			'omni/config.toml',
			`project = "test"
[capabilities]
enable = []`,
		);

		await runAgentsSync();

		expect(existsSync('.omni/generated')).toBe(true);
		expect(existsSync('.claude/skills')).toBe(true);
		expect(existsSync('.cursor/rules')).toBe(true);
	});

	test('should generate rules.md with no capabilities', async () => {
		// Create minimal config
		await Bun.write(
			'omni/config.toml',
			`project = "test"
[capabilities]
enable = []`,
		);

		await runAgentsSync();

		expect(existsSync('.omni/generated/rules.md')).toBe(true);
		const content = await Bun.file('.omni/generated/rules.md').text();
		expect(content).toContain('# Active Rules');
		expect(content).toContain('Generated by OmniDev');
	});

	test('should sync skills to .claude/skills/', async () => {
		// Create a test capability with a skill
		const capPath = 'omni/capabilities/test-cap';
		mkdirSync(join(capPath, 'skills', 'test-skill'), { recursive: true });

		await Bun.write(
			join(capPath, 'capability.toml'),
			`[capability]
id = "test-cap"
name = "Test Capability"
version = "1.0.0"
description = "A test capability"`,
		);

		await Bun.write(
			join(capPath, 'skills', 'test-skill', 'SKILL.md'),
			`---
name: test-skill
description: "A test skill"
---

Do something useful.`,
		);

		await Bun.write(
			'omni/config.toml',
			`project = "test"
[capabilities]
enable = ["test-cap"]`,
		);

		await runAgentsSync();

		expect(existsSync('.claude/skills/test-skill/SKILL.md')).toBe(true);
		const skillContent = await Bun.file('.claude/skills/test-skill/SKILL.md').text();
		expect(skillContent).toContain('name: test-skill');
		expect(skillContent).toContain('description: "A test skill"');
		expect(skillContent).toContain('Do something useful.');
	});

	test('should sync multiple skills', async () => {
		// Create a test capability with multiple skills
		const capPath = 'omni/capabilities/test-cap';
		mkdirSync(join(capPath, 'skills', 'skill-one'), { recursive: true });
		mkdirSync(join(capPath, 'skills', 'skill-two'), { recursive: true });

		await Bun.write(
			join(capPath, 'capability.toml'),
			`[capability]
id = "test-cap"
name = "Test Capability"
version = "1.0.0"
description = "A test capability"`,
		);

		await Bun.write(
			join(capPath, 'skills', 'skill-one', 'SKILL.md'),
			`---
name: skill-one
description: "First skill"
---

First skill content.`,
		);

		await Bun.write(
			join(capPath, 'skills', 'skill-two', 'SKILL.md'),
			`---
name: skill-two
description: "Second skill"
---

Second skill content.`,
		);

		await Bun.write(
			'omni/config.toml',
			`project = "test"
[capabilities]
enable = ["test-cap"]`,
		);

		await runAgentsSync();

		expect(existsSync('.claude/skills/skill-one/SKILL.md')).toBe(true);
		expect(existsSync('.claude/skills/skill-two/SKILL.md')).toBe(true);
	});

	test('should sync rules to .cursor/rules/', async () => {
		// Create a test capability with a rule
		const capPath = 'omni/capabilities/test-cap';
		mkdirSync(join(capPath, 'rules'), { recursive: true });

		await Bun.write(
			join(capPath, 'capability.toml'),
			`[capability]
id = "test-cap"
name = "Test Capability"
version = "1.0.0"
description = "A test capability"`,
		);

		await Bun.write(
			join(capPath, 'rules', 'test-rule.md'),
			`# Test Rule

Always do X when Y.`,
		);

		await Bun.write(
			'omni/config.toml',
			`project = "test"
[capabilities]
enable = ["test-cap"]`,
		);

		await runAgentsSync();

		expect(existsSync('.cursor/rules/omnidev-test-rule.mdc')).toBe(true);
		const ruleContent = await Bun.file('.cursor/rules/omnidev-test-rule.mdc').text();
		expect(ruleContent).toContain('# Test Rule');
		expect(ruleContent).toContain('Always do X when Y.');
	});

	test('should sync multiple rules', async () => {
		// Create a test capability with multiple rules
		const capPath = 'omni/capabilities/test-cap';
		mkdirSync(join(capPath, 'rules'), { recursive: true });

		await Bun.write(
			join(capPath, 'capability.toml'),
			`[capability]
id = "test-cap"
name = "Test Capability"
version = "1.0.0"
description = "A test capability"`,
		);

		await Bun.write(join(capPath, 'rules', 'rule-one.md'), '# Rule One\n\nContent one.');
		await Bun.write(join(capPath, 'rules', 'rule-two.md'), '# Rule Two\n\nContent two.');

		await Bun.write(
			'omni/config.toml',
			`project = "test"
[capabilities]
enable = ["test-cap"]`,
		);

		await runAgentsSync();

		expect(existsSync('.cursor/rules/omnidev-rule-one.mdc')).toBe(true);
		expect(existsSync('.cursor/rules/omnidev-rule-two.mdc')).toBe(true);
	});

	test('should include rules in rules.md', async () => {
		// Create a test capability with a rule
		const capPath = 'omni/capabilities/test-cap';
		mkdirSync(join(capPath, 'rules'), { recursive: true });

		await Bun.write(
			join(capPath, 'capability.toml'),
			`[capability]
id = "test-cap"
name = "Test Capability"
version = "1.0.0"
description = "A test capability"`,
		);

		await Bun.write(
			join(capPath, 'rules', 'important-rule.md'),
			`# Important Rule

Follow this carefully.`,
		);

		await Bun.write(
			'omni/config.toml',
			`project = "test"
[capabilities]
enable = ["test-cap"]`,
		);

		await runAgentsSync();

		const rulesContent = await Bun.file('.omni/generated/rules.md').text();
		expect(rulesContent).toContain('## important-rule (from test-cap)');
		expect(rulesContent).toContain('# Important Rule');
		expect(rulesContent).toContain('Follow this carefully.');
	});

	test('should handle capabilities with no skills or rules', async () => {
		// Create a test capability with no skills or rules
		const capPath = 'omni/capabilities/empty-cap';
		mkdirSync(capPath, { recursive: true });

		await Bun.write(
			join(capPath, 'capability.toml'),
			`[capability]
id = "empty-cap"
name = "Empty Capability"
version = "1.0.0"
description = "A capability with no content"`,
		);

		await Bun.write(
			'omni/config.toml',
			`project = "test"
[capabilities]
enable = ["empty-cap"]`,
		);

		await runAgentsSync();

		// Should still create directories and rules.md
		expect(existsSync('.omni/generated/rules.md')).toBe(true);
		expect(existsSync('.claude/skills')).toBe(true);
		expect(existsSync('.cursor/rules')).toBe(true);

		// No skills or rules files should be created
		const skillsFiles = readdirSync('.claude/skills');
		expect(skillsFiles.length).toBe(0);

		const rulesFiles = readdirSync('.cursor/rules');
		expect(rulesFiles.length).toBe(0);
	});

	test('should overwrite existing generated files', async () => {
		// Create initial config and run sync
		await Bun.write(
			'omni/config.toml',
			`project = "test"
[capabilities]
enable = []`,
		);

		await runAgentsSync();

		// Modify the generated file
		await Bun.write('.omni/generated/rules.md', 'Old content');

		// Run sync again
		await runAgentsSync();

		// Should have new content
		const content = await Bun.file('.omni/generated/rules.md').text();
		expect(content).toContain('# Active Rules');
		expect(content).not.toContain('Old content');
	});

	test('should respect profile-based capability filtering', async () => {
		// Create two capabilities
		const cap1Path = 'omni/capabilities/cap-one';
		const cap2Path = 'omni/capabilities/cap-two';
		mkdirSync(join(cap1Path, 'skills', 'skill-one'), { recursive: true });
		mkdirSync(join(cap2Path, 'skills', 'skill-two'), { recursive: true });

		await Bun.write(
			join(cap1Path, 'capability.toml'),
			`[capability]
id = "cap-one"
name = "Capability One"
version = "1.0.0"
description = "First capability"`,
		);

		await Bun.write(
			join(cap1Path, 'skills', 'skill-one', 'SKILL.md'),
			`---
name: skill-one
description: "First skill"
---

Content one.`,
		);

		await Bun.write(
			join(cap2Path, 'capability.toml'),
			`[capability]
id = "cap-two"
name = "Capability Two"
version = "1.0.0"
description = "Second capability"`,
		);

		await Bun.write(
			join(cap2Path, 'skills', 'skill-two', 'SKILL.md'),
			`---
name: skill-two
description: "Second skill"
---

Content two.`,
		);

		// Config enables only cap-one
		await Bun.write(
			'omni/config.toml',
			`project = "test"
default_profile = "default"
[capabilities]
enable = ["cap-one"]
[profiles.default]`,
		);

		await runAgentsSync();

		// Should only have skill-one
		expect(existsSync('.claude/skills/skill-one/SKILL.md')).toBe(true);
		expect(existsSync('.claude/skills/skill-two/SKILL.md')).toBe(false);
	});

	test('should handle capability loading errors gracefully', async () => {
		// Create a capability with invalid config
		const capPath = 'omni/capabilities/invalid-cap';
		mkdirSync(capPath, { recursive: true });

		await Bun.write(join(capPath, 'capability.toml'), 'invalid toml [[[');

		await Bun.write(
			'omni/config.toml',
			`project = "test"
[capabilities]
enable = []`,
		);

		// Should not throw
		await runAgentsSync();

		// Should still create base files
		expect(existsSync('.omni/generated/rules.md')).toBe(true);
	});
});
