import { describe, expect, test } from "bun:test";
import { generateAgentsTemplate } from "./agents";

describe("generateAgentsTemplate", () => {
	test("includes generated copy warning at the top", () => {
		const template = generateAgentsTemplate();

		expect(template.startsWith("> IMPORTANT: Do not edit this file directly.")).toBe(true);
		expect(template).toContain("Edit `OMNI.md` instead.");
	});

	test("generates AGENTS.md template with OmniDev section", () => {
		const template = generateAgentsTemplate();

		expect(template).toContain("# Project Instructions");
		expect(template).toContain("## OmniDev");
	});

	test("includes placeholder for project-specific instructions", () => {
		const template = generateAgentsTemplate();

		expect(template).toContain("<!-- Add your project-specific instructions here -->");
	});

	test("includes comment about sync population", () => {
		const template = generateAgentsTemplate();

		expect(template).toContain(
			"<!-- This section is populated during sync with capability rules and docs -->",
		);
	});
});
