/**
 * Template for CLAUDE.md (Claude provider)
 * Creates a minimal file - actual content is generated during sync from OMNI.md + instructions
 */
export function generateClaudeTemplate(): string {
	return `> IMPORTANT: Do not edit this file directly. Edit \`OMNI.md\` instead. This file is a generated copy of \`OMNI.md\` and is ephemeral. Any persistent change must be made in \`OMNI.md\`.

# Project Instructions

<!-- Add your project-specific instructions here -->
`;
}
