import type { ProviderAdapter, ProviderId } from "@omnidev-ai/core";
import { readEnabledProviders } from "@omnidev-ai/core";
import { claudeCodeAdapter } from "./claude-code/index";
import { codexAdapter } from "./codex/index";
import { cursorAdapter } from "./cursor/index";
import { opencodeAdapter } from "./opencode/index";
import type { WriterBackedProviderAdapter } from "./types";

export interface AdapterRegistry {
	adapters: Map<ProviderId, WriterBackedProviderAdapter>;
	get(id: ProviderId): WriterBackedProviderAdapter | undefined;
	getAll(): WriterBackedProviderAdapter[];
}

/**
 * All built-in adapters, keyed by their ID.
 */
const builtInAdapters: WriterBackedProviderAdapter[] = [
	claudeCodeAdapter,
	codexAdapter,
	cursorAdapter,
	opencodeAdapter,
];

const adapterMap = new Map<ProviderId, WriterBackedProviderAdapter>(
	builtInAdapters.map((adapter) => [adapter.id, adapter]),
);

function normalizeOutputPath(path: string): string {
	return path.replace(/\\/g, "/");
}

function outputPathToGitignoreEntry(path: string): string {
	const normalized = normalizeOutputPath(path);
	const segments = normalized.split("/").filter(Boolean);
	const firstSegment = segments[0];

	if (firstSegment?.startsWith(".") && segments.length > 1) {
		return `${firstSegment}/`;
	}

	return normalized;
}

function uniqueEntries(entries: string[]): string[] {
	return [...new Set(entries)];
}

/**
 * Get an adapter by its ID.
 */
export function getAdapter(id: ProviderId): WriterBackedProviderAdapter | undefined {
	return adapterMap.get(id);
}

/**
 * Get all available adapters.
 */
export function getAllAdapters(): WriterBackedProviderAdapter[] {
	return builtInAdapters;
}

/**
 * Get adapters that are currently enabled in the user's local state.
 */
export async function getEnabledAdapters(): Promise<ProviderAdapter[]> {
	const enabledIds = await readEnabledProviders();
	return enabledIds
		.map((id) => adapterMap.get(id))
		.filter((a): a is WriterBackedProviderAdapter => a != null);
}

/**
 * Return gitignore entries for the files and directories generated by providers.
 */
export function getProviderGitignoreEntries(providerIds: ProviderId[]): string[] {
	const outputPaths = providerIds.flatMap((id) => {
		const adapter = adapterMap.get(id);
		if (!adapter) {
			return [];
		}

		return [
			...adapter.writers.map((config) => config.outputPath),
			...(adapter.additionalOutputPaths ?? []),
		];
	});

	return uniqueEntries(outputPaths.map(outputPathToGitignoreEntry));
}
